# Generated by Django 2.2.16 on 2020-10-09 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20201009_0625'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.IntegerField(choices=[(0, 'How to'), (1, 'Lessons Learnt'), (2, 'Resources')], default=1),
            preserve_default=False,
        ),
    ]
