# Generated by Django 2.2.16 on 2020-10-09 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_post_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collection',
            name='is_admin',
        ),
        migrations.AddField(
            model_name='collection',
            name='is_private',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='collection',
            name='tags',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='tags',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
